import fs from "fs";
import path from "path";

const BASE_PATH = "C:\\Users\\cyber\\Desktop\\Capturas_Video_SASE";
const OUTPUT_FILE = path.join(
  BASE_PATH,
  "Guion_Consolidado_Protocolos_SASE.html"
);

function getImageB64(fileName) {
  try {
    const filePath = path.join(BASE_PATH, fileName);
    // Explicit boolean check
    if (fs.existsSync(filePath) === true) {
      console.log(`Embedding: ${fileName}`);
      const fileData = fs.readFileSync(filePath);
      const b64 = fileData.toString("base64");
      return `data:image/png;base64,${b64}`;
    } else {
      console.warn(`Warning: Image not found: ${fileName} at path ${filePath}`);
      // Use an absolute URL for placeholder so PDF renderer can find it?
      // Better to use inline SVG for placeholder to guarantee visibility
      return "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA4MDAgNDUwIiB3aWR0aD0iODAwIiBoZWlnaHQ9IjQ1MCI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2VlZSIvPjx0ZXh0IHg9IjUwJSIgeT0iNTAlIiBkeT0iLjNlbSIgZmlsbD0iI2FhYSIgZm9udC1zaXplPSIzMCIgZm9udC1mYW1pbHk9ImFyaWFsIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5JbWFnZW4gTm8gRW5jb250cmFkYTwvdGV4dD48L3N2Zz4=";
    }
  } catch (e) {
    console.error(`Error reading ${fileName}:`, e);
    return "";
  }
}

// List of images to include (must match filenames generated by capture script)
const images = {
  "01": "01_dashboard_protocolos.png",
  "02": "02_card_protocolo_salud_convulsion.png",
  "03": "03_modal_protocolo_convulsion.png",
  "04": "04_card_protocolo_pc_sismo.png",
  "05": "05_modal_protocolo_sismo.png",
  "06": "06_registro_incidencia_docente.png",
  "07": "07_protocolo_activado_desde_incidencia.png",
  "08": "08_dashboard_direccion_evento.png",
  "09": "09_registro_trazabilidad.png",
};

// Check if images exist before generating
console.log(`Checking images in: ${BASE_PATH}`);
let missing = false;
for (const key in images) {
  const p = path.join(BASE_PATH, images[key]);
  if (!fs.existsSync(p)) {
    console.error(`MISSING: ${images[key]}`);
    missing = true;
  } else {
    const stats = fs.statSync(p);
    console.log(`OK: ${images[key]} (${stats.size} bytes)`);
  }
}

if (missing) {
  console.error(
    "Some images are missing. Please re-run the capture script first."
  );
  // We will still generate, but with placeholders.
}

const htmlContent = `<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SASE-310: Sistema de Protocolos Institucionales</title>
    <style>
        body { font-family: 'Segoe UI', system-ui, sans-serif; max-width: 900px; margin: 0 auto; padding: 40px; background-color: #f8fafc; color: #1e293b; }
        .container { background: white; padding: 50px; border-radius: 20px; box-shadow: 0 10px 40px rgba(0,0,0,0.08); }
        
        /* Cover */
        .cover { text-align: center; margin-bottom: 60px; padding-bottom: 40px; border-bottom: 4px solid #3b82f6; }
        h1 { color: #0f172a; font-size: 2.5rem; margin-bottom: 10px; letter-spacing: -0.05em; }
        .subtitle { font-size: 1.25rem; color: #64748b; font-weight: 300; }
        
        /* Sections */
        h2 { color: #3b82f6; margin-top: 50px; font-size: 1.5rem; display: flex; align-items: center; gap: 12px; border-left: 4px solid #3b82f6; padding-left: 15px; }
        .meta { display: flex; gap: 20px; margin-bottom: 20px; font-size: 0.9rem; color: #64748b; background: #f1f5f9; padding: 10px 20px; border-radius: 8px; }
        .meta-item strong { color: #334155; }
        
        /* Images */
        figure { margin: 0; padding: 0; transition: transform 0.3s ease; }
        figure:hover { transform: translateY(-5px); }
        /* Force image display */
        img { width: 100%; height: auto; display: block; border-radius: 12px; border: 1px solid #cbd5e1; box-shadow: 0 10px 30px -5px rgba(0, 0, 0, 0.1); background-color: #eee; min-height: 200px; }
        figcaption { margin-top: 10px; font-size: 0.85rem; color: #94a3b8; text-align: center; font-style: italic; }

        /* Badges */
        .badge { display: inline-block; padding: 4px 10px; border-radius: 99px; font-size: 0.75rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; }
        .badge-convivencia { background: #fee2e2; color: #991b1b; }
        .badge-salud { background: #ffedd5; color: #9a3412; }
        .badge-pc { background: #dbeafe; color: #1e40af; }

        .footer { margin-top: 80px; text-align: center; color: #cbd5e1; font-size: 0.8rem; }
    </style>
</head>
<body>
    <div class="container">
        <div class="cover">
            <h1>SASE-310</h1>
            <p class="subtitle">Manual Operativo Vivo: Sistema de Protocolos</p>
            <p style="margin-top: 20px; color: #94a3b8; font-size: 0.9rem;">Documento de Evidencia Técnica y Operativa</p>
        </div>

        <!-- 1 -->
        <h2>01. Dashboard de Protocolos</h2>
        <div class="meta">
            <div class="meta-item"><strong>Archivo:</strong> ${
              images["01"]
            }</div>
            <div class="meta-item"><strong>Objetivo:</strong> Acceso centralizado</div>
        </div>
        <p>Vista general del módulo donde el personal puede filtrar protocolos por categoría (Convivencia, Salud, Protección Civil) y buscar situaciones específicas en tiempo real.</p>
        <figure>
            <img src="${getImageB64(images["01"])}" alt="Dashboard Protocolos">
        </figure>

        <!-- 2 -->
        <h2>02. Tarjeta: Crisis Convulsiva <span class="badge badge-salud">Salud</span></h2>
        <div class="meta">
            <div class="meta-item"><strong>Archivo:</strong> ${
              images["02"]
            }</div>
            <div class="meta-item"><strong>Valor:</strong> Identificación rápida</div>
        </div>
        <p>Diseño de tarjeta con código de color naranja (Salud) que permite identificar el protocolo visualmente en situaciones de estrés.</p>
        <figure>
            <img src="${getImageB64(images["02"])}" alt="Card Convulsión">
        </figure>

        <!-- 3 -->
        <h2>03. Guía Operativa: Convulsión</h2>
        <div class="meta">
             <div class="meta-item"><strong>Archivo:</strong> ${
               images["03"]
             }</div>
             <div class="meta-item"><strong>Función:</strong> Instrucción paso a paso</div>
        </div>
        <p>Modal de "Acción Guiada" que muestra qué hacer y, críticamente, qué NO hacer (advertencias en rojo) para proteger la integridad del alumno.</p>
        <figure>
            <img src="${getImageB64(images["03"])}" alt="Modal Convulsión">
        </figure>

        <!-- 4 -->
        <h2>04. Tarjeta: Sismo <span class="badge badge-pc">Protección Civil</span></h2>
        <div class="meta">
              <div class="meta-item"><strong>Archivo:</strong> ${
                images["04"]
              }</div>
              <div class="meta-item"><strong>Contexto:</strong> Emergencia masiva</div>
        </div>
        <p>Tarjeta de protocolo de Protección Civil (Azul). Su ubicación prioritaria facilita el acceso durante simulacros o eventos reales.</p>
        <figure>
            <img src="${getImageB64(images["04"])}" alt="Card Sismo">
        </figure>

        <!-- 5 -->
        <h2>05. Guía Operativa: Sismo</h2>
        <div class="meta">
              <div class="meta-item"><strong>Archivo:</strong> ${
                images["05"]
              }</div>
              <div class="meta-item"><strong>Acción:</strong> Repliegue y Evacuación</div>
        </div>
        <p>Instrucciones claras para docentes frente a grupo: mantener la calma, zona de seguridad y rutas de evacuación.</p>
        <figure>
            <img src="${getImageB64(images["05"])}" alt="Modal Sismo">
        </figure>

        <!-- 6 -->
        <h2>06. Registro de Incidencia</h2>
        <div class="meta">
              <div class="meta-item"><strong>Archivo:</strong> ${
                images["06"]
              }</div>
              <div class="meta-item"><strong>Rol:</strong> Docente</div>
        </div>
        <p>Interfaz de captura rápida donde el docente reporta un evento (ej. "Convulsión en patio") usando voz o texto.</p>
        <figure>
            <img src="${getImageB64(images["06"])}" alt="Registro Incidencia">
        </figure>

        <!-- 7 -->
        <h2>07. Activación Automática</h2>
        <div class="meta">
              <div class="meta-item"><strong>Archivo:</strong> ${
                images["07"]
              }</div>
              <div class="meta-item"><strong>Inteligencia:</strong> Detección proactiva</div>
        </div>
        <p>El sistema detecta palabras clave o tipos de riesgo y <strong>sugiere/activa</strong> el protocolo correspondiente inmediatamente después del registro.</p>
        <figure>
            <img src="${getImageB64(images["07"])}" alt="Activación Automática">
        </figure>

        <!-- 8 -->
        <h2>08. Dashboard Dirección</h2>
        <div class="meta">
              <div class="meta-item"><strong>Archivo:</strong> ${
                images["08"]
              }</div>
              <div class="meta-item"><strong>Visión:</strong> Panorama Institucional</div>
        </div>
        <p>La dirección monitoriza en tiempo real los eventos registrados y activaciones de protocolo en el plantel.</p>
        <figure>
            <img src="${getImageB64(images["08"])}" alt="Dashboard Dirección">
        </figure>

        <!-- 9 -->
        <h2>09. Trazabilidad y Bitácora</h2>
        <div class="meta">
              <div class="meta-item"><strong>Archivo:</strong> ${
                images["09"]
              }</div>
              <div class="meta-item"><strong>Seguridad:</strong> Auditoría Jurídica</div>
        </div>
        <p>Registro inmutable de acciones: quién registró, a qué hora, qué protocolo se consultó y qué se hizo. Base para la defensa jurídica de la escuela.</p>
        <figure>
            <img src="${getImageB64(images["09"])}" alt="Trazabilidad">
        </figure>

        <div class="footer">
            SASE-310 © 2026 | Generado por Antigravity IA | ${new Date().toLocaleString()}
        </div>
    </div>
</body>
</html>`;

fs.writeFileSync(OUTPUT_FILE, htmlContent);
console.log(`HTML Generated at: ${OUTPUT_FILE}`);
