-- Create Feedback Table
create table if not exists system_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users,
  email text,
  type text check (type in ('bug', 'suggestion', 'ux')),
  comment text not null,
  url text,
  user_agent text,
  resolved boolean default false
);

-- Create Audit Table (Caja Negra)
create table if not exists auditoria (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  usuario_id uuid references auth.users,
  email_usuario text,
  rol_usuario text,
  tipo_accion text check (tipo_accion in ('CONSULTA', 'ACTUALIZACION', 'CREACION', 'ELIMINACION', 'LOGIN_GOD_MODE')),
  descripcion_accion text,
  tabla_objetivo text,
  id_registro_objetivo text,
  nombre_alumno_objetivo text,
  valores_anteriores jsonb,
  nuevos_valores jsonb
);

-- RLS Policies (Optional but recommended, for now public for dev speed)
alter table system_feedback enable row level security;
create policy "Enable all access for authenticated users" on system_feedback for all using (true) with check (true);

alter table auditoria enable row level security;
create policy "Enable insert for all, select for admins" on auditoria for all using (true) with check (true);
