export enum UserRole {
  DIRECTIVO = "directivo",
  SUBDIRECCION = "subdireccion",
  DOCENTE = "docente",
  DOCENTE_TUTOR = "docente_tutor",
  PREFECTURA = "prefectura",
  ORIENTACION = "orientacion",
  TRABAJO_SOCIAL = "trabajo_social",
  MEDICO_ESCOLAR = "medico_escolar",
  UDEII = "udeii",
  PROMOTORA_LECTURA = "promotora_lectura",
  SECRETARIA = "secretaria",
  GUEST = "guest",
  DEVELOPER = "developer",
  SYSTEM_ADMIN = "system_admin",
}

export interface PermisosSASE {
  can_view_names: boolean;
  can_register: boolean;
  can_edit: boolean;
  can_close: boolean;
  can_escalate: boolean;
  can_view_audit: boolean;
  can_approve_staff: boolean;
  can_assign_groups: boolean;
  can_view_sensitive: boolean;
  can_manage_system: boolean;
}

export const RoleLabels: Record<UserRole, string> = {
  [UserRole.DIRECTIVO]: "Dirección",
  [UserRole.SUBDIRECCION]: "Subdirección",
  [UserRole.DOCENTE]: "Docente",
  [UserRole.DOCENTE_TUTOR]: "Docente Tutor",
  [UserRole.PREFECTURA]: "Prefectura",
  [UserRole.ORIENTACION]: "Orientación",
  [UserRole.TRABAJO_SOCIAL]: "Trabajo Social",
  [UserRole.MEDICO_ESCOLAR]: "Servicio Médico",
  [UserRole.SECRETARIA]: "Secretaría",
  [UserRole.UDEII]: "UDEII",
  [UserRole.PROMOTORA_LECTURA]: "Fomento a la Lectura",
  [UserRole.GUEST]: "Invitado",
  [UserRole.DEVELOPER]: "Desarrollador (Acceso Total)",
  [UserRole.SYSTEM_ADMIN]: "Soporte Nivel 3 (Root)",
};

export enum CaseState {
  OBSERVADO = "En Seguimiento Preventivo", // 1-2 Incidents
  PATRON_DETECTADO = "Atención Prioritaria", // 3 Incidents
  EN_ANALISIS = "En Análisis de Trayectoria",
  INTERVENCION = "Acompañamiento Intensivo",
  SEGUIMIENTO = "Seguimiento Institucional",
  CERRADO = "Acompañamiento Concluido",
}

export enum IncidentType {
  ASISTENCIA = "Asistencia / Falta",
  RETARDO = "Retardo",
  CONDUCTA = "Observación de Convivencia", // Marco para la Convivencia (Faltas leves/graves)
  ACADEMICO = "Observación Académica",
  SALUD = "Atención Médica", // Incluye: Prevención de Adicciones / Si te drogas te dañas
  SOCIOEMOCIONAL = "Atención Socioemocional",
  UNIFORME = "Falta de Uniforme",
}

export interface Calificacion {
  materia: string;
  trimestre1?: number;
  trimestre2?: number;
  trimestre3?: number;
  promedioFinal?: number;
}

export type DocumentType =
  | "HECHOS"
  | "MINUTA"
  | "ACUERDO"
  | "DISTANCIA"
  | "CITATORIO";

export interface DocumentoInstitucional {
  id: string;
  tipo: DocumentType;
  folio: string;
  fecha: string;
  titulo: string;
  contenido: string; // Markdown or plain text
  narracionIA?: string; // Generated by AI
  firmas: string[]; // List of roles/names that sign
  studentId: string;
  creado_por: string;
}

export interface Incident {
  id: string;
  studentId: string;
  type: IncidentType;
  description: string;
  date: string; // ISO string
  reportedBy: string; // Role or Name
  subject?: string; // Optional: Academic subject
  comments?: string; // Optional: Additional supervisor comments
  evidence?: string[]; // Optional: URLs to images/docs
  reporta?: string; // Institutional reporter name
  estado?: string;
  clasificacion?: string;
  fecha?: string;
  reportadoPorDocente?: string;
  prefectoAsignado?: string;
  grupoId?: string;
  gravedad?: "leve" | "media" | "grave" | "critica"; // Impacto semáforo
  notificado_whatsapp?: boolean;
}

export interface Justificante {
  id: string;
  folio: string;
  startDate: string;
  endDate: string;
  reason: "Médico" | "Social" | "Legal";
  description: string;
  issuedBy: string;
  issuedAt: string;
}

export interface BAPInfo {
  hasBAP: boolean;
  diagnosisPrivate: string;
  accommodations: string[];
  lastUpdated: string; // ISO
}

export type SolicitudPriority = "baja" | "normal" | "alta" | "urgente";
export type SolicitudStatus =
  | "pendiente"
  | "en_proceso"
  | "completado"
  | "cancelado";

export interface Solicitud {
  id: string;
  tipo: string;
  descripcion: string;
  asignado_a?: string;
  asignado_nombre?: string;
  prioridad: SolicitudPriority;
  estado: SolicitudStatus;
  fecha_limite?: string;
  alumno_id?: string;
  alumno_nombre?: string;
  created_at?: string;
  created_by?: string;
}

export interface GuardianInfo {
  name: string;
  relationship: string;
  phonePrimary: string;
  phoneSecondary?: string;
  email?: string;
  address?: string;
  details?: any; // Para metadatos extra como 'is_udeii'
  photoUrl?: string; // New: Foto del Responsable
}

export enum CredencialStatus {
  ENTREGADA = "entregada",
  EN_TRAMITE = "en_tramite",
  EXTRAVIADA = "extraviada",
  NO_SOLICITADA = "no_solicitada",
}

export enum EstadoObjetoRetenido {
  RETENIDO = "retenido",
  DEVUELTO_ALUMNO = "devuelto al alumno",
  ENTREGADO_PADRE = "entregado a padre",
}

export interface ObjetoRetenido {
  id: string;
  alumno_id?: string;
  studentId?: string;
  studentName?: string;
  group?: string;
  objeto: string;
  motivo: string;
  fecha: string; // ISO string
  responsable_id?: string;
  responsableId?: string;
  responsableNombre: string;
  responsableRol: UserRole;
  estado: EstadoObjetoRetenido;
  incidencia_id?: string;
  incidenciaId?: string; // Relación con la incidencia generada
  created_at?: string;
  // Nuevos campos para cadena de custodia completa
  fechaDevolucion?: string;
  entregadoA?: string;
  entregadoPor?: string;
  lugarRetencion?: string;
  categoria?: string;
  observaciones?: string;
  evidenciaUrl?: string;
  autorizadoPor?: string;
}

export interface SocioeconomicData {
  familyType: "Nuclear" | "Extendida" | "Monoparental" | "Otra";
  incomeLevel: "Bajo" | "Medio-Bajo" | "Medio" | "Alto";
  internetAccess: boolean;
  distanceToSchool: string; // Ej: "0-5km", "5-10km", "10+km"
  housingType: "Propia" | "Rentada" | "Prestada";
}

export interface GamificacionData {
  total_puntos: number;
  escaneos_realizados: number;
  nickname?: string;
}

export interface Student {
  id: string;
  matricula: string;
  curp?: string;
  name: string;
  birthdate?: string; // ISO Date
  gender?: "M" | "F" | "X";
  previousGpa?: number;
  group: string;
  avatar: string;
  caseState: CaseState;
  incidents: Incident[];
  medicalAlerts?: string[];
  medicalHistory?: string; // Full medical history text
  // New Modules
  guardianInfo?: GuardianInfo; // Protected: Secretariat/Tutor only
  lastModifiedBy?: string;
  lastModifiedAt?: string; // ISO Date
  bapInfo?: BAPInfo;
  justificantes: Justificante[];
  
  // Risk Semaphore Institucional
  puntajeRiesgo?: number;
  estadoSemaforo?: string;
  fechaCalculoRiesgo?: string;
  
  // Dimensiones de Riesgo Institucional
  riesgoDisciplina?: number;
  riesgoAsistencia?: number;
  riesgoAcademico?: number;
  riesgoSocioemocional?: number;

  // New: Advanced Management
  calificaciones?: Calificacion[];
  documentos?: DocumentoInstitucional[];
  isDistancia?: boolean; // Modo a Distancia
  credencialStatus?: CredencialStatus;
  documentationComplete?: boolean;
  socioeconomicData?: SocioeconomicData;
  gamificacion?: GamificacionData;
  objetosRetenidos?: ObjetoRetenido[];
}

export type ProtocolType =
  | "convivencia"
  | "salud"
  | "proteccion_civil"
  | "apoyo"
  | "legal"
  | "seguridad";

export interface Protocol {
  id: string;
  titulo: string;
  tipo: ProtocolType;
  objetivo: string;
  activacion: string;
  fuente: string;
  roles_responsables: string[];
  icono: string;
}

export interface ProtocolStep {
  id: string;
  protocolo_id: string;
  orden: number;
  accion: string;
  descripcion_detalle?: string;
  es_advertencia: boolean;
  rol_responsable?: string;
}

export interface ProtocolActivation {
  id: string;
  protocolo_id: string;
  incidencia_id?: string;
  usuario_id: string;
  fecha_inicio: string;
  estado: "activo" | "finalizado";
  paso_actual?: number;
}



export enum AppModule {
  DASHBOARD = "dashboard",
  INSCRIPCIONES = "inscripciones",
  ARCHIVO = "archivo",
  AGENDA = "agenda",
  REPORTES = "reportes",
  NOTIFICATIONS = "notifications",
  BITACORA = "bitacora",
  SOLICITUDES = "solicitudes",
  REPORTES_DOCENTES = "reportes_docentes",
  PROTOCOLOS = "protocolos",
  APROBACIONES_PERSONAL = "aprobaciones_personal",
  CALIFICACIONES = "calificaciones",
  DOCUMENTACION = "documentacion",
  MIS_GRUPOS = "mis_grupos",
  SUBDIRECCION = "subdireccion",
  SALUD = "salud",
  UDEII_TRACKER = "udeii_tracker",
  TRABAJO_SOCIAL_TRACKER = "trabajo_social_tracker",
  LECTURA_TRACKER = "lectura_tracker",
  DEVELOPER = "developer",
  EXPEDIENTES = "expedientes",
  ASISTENCIA = "asistencia",
  NOT_FOUND = "not_found",
  HOME = "home",
  WELCOME = "welcome",
  REGISTRO_PERSONAL = "registro_personal",
  PLANEACION_NEM = "planeacion_nem",
  IA_SASE = "ia_sase",
  OBJETOS_RETENIDOS = "objetos_retenidos",
}

export interface Group {
  id: string;
  nombre: string;
  tutor_id?: string;
  ciclo_escolar: string;
}

export interface TeacherAssignment {
  id: string;
  profesor_id: string;
  grupo_id: string;
  materia: string;
}

export interface Notification {
  id: string;
  title: string;
  message: string;
  read: boolean;
  time: string;
  type?: "info" | "warning" | "success" | "error" | "SYSTEM";
  actionModule?: AppModule;
  actionData?: any;
  targetRole?: UserRole;
}

export interface Suministro {
  id: string;
  nombre: string;
  cantidad: number;
  cantidadMaxima: number;
  categoria: string;
  unidad: string;
}

export interface DailyStats {
  attendanceCount: number;
  lateCount: number;
}

export type AuditActionType =
  | "CONSULTA"
  | "ACTUALIZACION"
  | "CREACION"
  | "ELIMINACION";

export interface SystemNotice {
  id: string;
  type: "ACTUALIZACION_DATOS" | "CREDENCIAL_TRAMITE" | "ACTUALIZACION_TELEFONO";
  studentId: string;
  studentName: string;
  description: string;
  requestedBy: string;
  date: string;
  resolved: boolean;
  priority: "ALTA" | "MEDIA" | "BAJA";
}
