-- Integración de datos diagnósticos y retroalimentación para 1º D
-- Fuente: CSV (Calificaciones) y DOCX (Retroalimentación detallada)

DELETE FROM examenes_trimestre WHERE grupo = '1º D';

INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('ALVAREZ CASASOLA ANDREA', '1º D', 7.5, 'DIAGNÓSTICO: Rescata puntos por lógica en sumas y buena representación gráfica. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('BRAVO JIMENEZ ALAN ANTONIO', '1º D', 8.0, 'DIAGNÓSTICO: Dominio de la representación del huerto escolar; identificó las 12 plantas. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('CARRANZA MARTINEZ MAURICIO ELIEL', '1º D', 8.0, 'DIAGNÓSTICO: Excelente uso de colores para validar equivalencias; explica el reparto. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('CERVANTES ESQUIVEL GUADALUPE ABIGAIL', '1º D', 8.0, 'DIAGNÓSTICO: Se valora su intuición visual para identificar fracciones mayores. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('CHAVEZ ROSAS AMIXI', '1º D', 7.5, 'DIAGNÓSTICO: Lógica de resta homogénea impecable; excelente interpretación de magnitudes. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('ESPEJEL PALESTINA KELLY BRIGITTE', '1º D', 8.0, 'DIAGNÓSTICO: Buen manejo de representaciones gráficas; éxito en el reactivo de reparto. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('ESTRADA CUAUTLE DEREK ADONAI', '1º D', 9.5, 'DIAGNÓSTICO: Identificación perfecta de la relación de 12 tortillas para 4 platos. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('GARCIA ARREOLA KEVIN', '1º D', 7.5, 'DIAGNÓSTICO: Lógica sólida en proporcionalidad básica y equivalencias. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('GARCIA ABEL JOSAFAT', '1º D', 7.5, 'DIAGNÓSTICO: Uso correcto de barras iguales para demostrar comparaciones visuales. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('GOMEZ VARELA KARIM', '1º D', 10.0, 'DIAGNÓSTICO: Destaca en la representación visual y resolución de problemas de reparto. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('HERNANDEZ ARTEAGA ALEJANDRO DEMIAN', '1º D', 8.5, 'DIAGNÓSTICO: Dominio de la representación del huerto escolar; gran base matemática. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('HERNANDEZ CRUZ VICTOR DANIEL', '1º D', 8.0, 'DIAGNÓSTICO: Explica correctamente por qué una fracción es mayor que otra. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('HERNANDEZ RENDON ASHLEY DARIANA', '1º D', 8.0, 'DIAGNÓSTICO: Se valora su capacidad de igualación visual de denominadores. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('HERNANDEZ SANCHEZ ERIKA NATALIA', '1º D', 8.0, 'DIAGNÓSTICO: Lógica de resta homogénea impecable (2/5); buena interpretación visual. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('LORENZO REBOLLO YAMILETH SARAHI', '1º D', 7.5, 'DIAGNÓSTICO: Se rescata su lógica cualitativa en problemas contextuales de reparto. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('MADRIGAL DE NADA SAMANTHA CRISTAL', '1º D', 8, 'DIAGNÓSTICO: Identificó la relación de 12 tortillas; uso correcto de barras para sumas.', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('MENDOZA SANCHEZ IAN ANDRES', '1º D', 3.0, 'DIAGNÓSTICO: Explicación clara sobre magnitud ("se pasa de la mitad"). | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('MORALES PEREZ KEVIN ALEJANDRO', '1º D', 8.0, 'DIAGNÓSTICO: Uso efectivo de colores para identificar fracciones y sumas de partes iguales. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('OROCIO VELAZQUEZ KIMBERLY MICHELLE', '1º D', 8.0, 'DIAGNÓSTICO: Excelente interpretación de problemas de reparto; identificó las 24 tortillas. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('PICHARDO VARGAS GENESIS ELIM', '1º D', 8.0, 'DIAGNÓSTICO: Se rescata su uso de colores para identificar fracciones equivalentes. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('RAMIREZ ROSALES SANTIAGO ARTURO', '1º D', 6.5, 'DIAGNÓSTICO: Lógica adecuada en noción parte-todo; rescata puntaje en reparto. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('RANGEL LOERA DOMINICK EDUARDO', '1º D', 7.5, 'DIAGNÓSTICO: Demuestra buena comprensión de la representación gráfica del huerto. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('RUBIO PACHECO KEVIN YAEL', '1º D', 8.0, 'DIAGNÓSTICO: Logra identificar relaciones proporcionales simples con apoyo visual. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);
INSERT INTO examenes_trimestre (nombre_alumno, grupo, calificacion_final, feedback, grado) VALUES ('TREVIÑO HINOJOSA LEOBALDO', '1º D', 8.0, 'DIAGNÓSTICO: Éxito en representaciones de barras; comprende la relación parte-todo. | RETROALIMENTACIÓN EXAMEN: [Mejora: Revisar procedimientos señalados en rojo.] [Plan: Practicar igualación de denominadores y justificar procesos.]', 1);

-- Registro en auditoria
INSERT INTO auditoria (tipo_accion, tabla_objetivo, descripcion_accion)
VALUES ('IMPORT_DIAGNOSTICO_1D', 'examenes_trimestre', 'Importación masiva de calificaciones y retroalimentación para el grupo 1º D desde CSV y DOCX.');
